config/routes.rb
Rails.application.routes.draw do
  root 'bathrooms#index'
  resources :bathrooms, only: [:index, :new, :create, :show] do
    resources :reviews, only: [:index, :new, :create]
  end
end

app/models/bathroom.rb
class Bathroom < ActiveRecord::Base
  has_many :reviews

  validates :location_name, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip, presence: true
  validates :zip, length: { is: 5 }
  validates :zip, numericality: { only_integer: true }
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :bathroom

  validates :body, presence: true
  validates :rating, presence: true
  validates :rating, numericality: { only_integer: true }
  validates :rating, inclusion: { in: 1..5, message: "Must be between 1 -5" }
  validates :bathroom_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bathrooms_controller.rb
class BathroomsController < ApplicationController
  def index
    @bathrooms = Bathroom.all
  end

  def show
    @bathroom = Bathroom.find(params[:id])
    @reviews = @bathroom.reviews
  end

  def new
    @bathroom = Bathroom.new
  end

  def create
    @bathroom = Bathroom.new(bathroom_params)

    if @bathroom.save
      redirect_to bathrooms_path
    else
      flash[:errors] = @bathroom.errors.full_messages.join(". ")
      render :new
    end
  end



  protected
  def bathroom_params
    params.require(:bathroom).permit(:location_name, :address, :city, :state, :zip, :description)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @bathroom = Bathroom.find(params[:bathroom_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @bathroom = Bathroom.find(params[:bathroom_id])
    @review.bathroom = @bathroom

    if @review.save
      redirect_to bathroom_path(@bathroom)
    else
      flash[:errors] = @review.errors.full_messages.join(". ")
      render :new
    end
  end

  protected
  def review_params
    params.require(:review).permit(:body, :rating, :bathroom_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bathrooms/index.html.erb
<h1>Bathrooms</h1>

<ul>
  <% @bathrooms.each do |bathroom| %>
    <li> <%= link_to bathroom.location_name, bathroom_path(bathroom) %> </li>
  <% end %>
</ul>

<%= link_to "Add bathroom", new_bathroom_path %>

app/views/bathrooms/new.html.erb
<h1>Add a Bathroom</h1>

 <%= form_for @bathroom do |f| %>
  <%= f.label :location_name %>
  <%= f.text_field :location_name %>
  <br>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <br>
  <%= f.label :city %>
  <%= f.text_field :city %>
  <br>
  <%= f.label :state %>
  <%= f.text_field :state %>
  <br>
  <%= f.label :zip %>
  <%= f.text_field :zip %>
  <br>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <br>
  <%= f.submit "Add Bathroom", class: "button" %>
 <% end %>

<%= link_to "Back to home", bathrooms_path %>

app/views/bathrooms/show.html.erb
<h1> <%= @bathroom.location_name %> </h1>
<ul>
  <li>
    <%= @bathroom.address%>,<%= @bathroom.city %>, <%= @bathroom.state %> <%= @bathroom.zip %>
  </li>
  <li>
    <%= @bathroom.description %>
  </li>
</ul>

<h3>Reviews</h3>
<ul>
  <% @reviews.each do |review| %>
  <li>
      rating: <%= review.rating %> - <%= review.body %>
  </li>

  <% end %>
</ul>

<%= link_to "Back", bathrooms_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Airpnp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |key, value| %>
  <%= value %>
<% end %>

<%= yield %>

</body>
</html>

app/views/reviews/new.html.erb
<h1>Add a Review </h1>
<%= form_for [@bathroom, @review] do |f| %>
  <%= f.label :body %>
  <%= f.text_field :body %>
  <br>
  <%= f.label :rating %>
  <%= f.text_field :rating %>
  <br>
  <%= f.submit "Add Review" %>
<% end %>